// This file was generated by a tool.
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyVersionAttribute("0.3.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.3.0.0")]
[assembly: AssemblyProductAttribute("RangeLog")]
[assembly: AssemblyCopyrightAttribute("Copyright 2009 Tom Opgenorth. All rights reserved.")]
            
